djinni:
  - .NET
  - Android
  - C++
  - Data Engineer
  - Data Science
  - DevOps
  - Flutter
  - Fullstack
  - Golang
  - Java
  - JavaScript
  - Kotlin
  - Node.js
  - PHP
  - Python
  - React Native
  - Ruby
  - Rust
  - Scala
  - iOS
