Djinni:
  - .NET # C# / .NET
  - Android
  - C++ # C / C++ / Embedded
  - Data Engineer
  - Data Science
  - DevOps
  - Flutter
  - Fullstack
  - Golang
  - Java
  - JavaScript # JavaScript / Front-End
  - Kotlin
  - Node.js
  - PHP
  - Python
  - React Native
  - Ruby
  - Rust
  - Scala
  - iOS
